import type { Metadata } from "next";

import "./globals.css";
import Navbar from "./components/Navbar";
import { fira_sans } from "./fonts";

// Configure Fira Sans for body text

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Apply the font variables to the body */}
      <body className={`${fira_sans.className} bg-black text-white `}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
